### ISSUE TITLE
Some emojis are not supported by shortname

### ISSUE THREAD

**Issue by M4rcos** [EricPKerr/react-native-emoji#14]
<Emoji name={'man-getting-massage'} />
<Emoji name={'man-getting-haircut'} />
<Emoji name={'woman-walking'} />
<Emoji name={'woman-running'} />
<Emoji name={'man_dancing'} />
<Emoji name={'man-golfing'} />
<Emoji name={'woman-golfing'} />
<Emoji name={'man-surfing'} />
<Emoji name={'woman-surfing'} />
<Emoji name={'man_rowing_boat'} />
<Emoji name={'man-swimming'} />
<Emoji name={'woman-swimming'} />
<Emoji name={'man-bouncing-ball'} />
<Emoji name={'woman-bouncing-ball'} />
<Emoji name={'man-lifting-weights'} />
<Emoji name={'woman-lifting-weights'} />
<Emoji name={'man-biking'} />
<Emoji name={'handball'} />
<Emoji name={'woman-playing-handball'} />
<Emoji name={'croissant'} />
<Emoji name={'pancakes'} />
<Emoji name={'bacon'} />
<Emoji name={'green_salad'} />
<Emoji name={'tumbler_glass'} />
<Emoji name={'musical_notes'} />
<Emoji name={'drum_with_drumsticks'} />

**Comment by M4rcos** [comment]
How can I help to get those working?

**Comment by EricPKerr** [comment]
`node-emoji` dependency will be updated to latest in next version. Thanks
