### ISSUE TITLE
Android emoji don't appear (juste stay with :name_of_emoji:)

### ISSUE THREAD

**Issue by theinvensi** [EricPKerr/react-native-emoji#16]
I install using `npm i -S react-native-emoji`

Even not asking I do a `react-native link`

My code is `<Text>(bla bla bla <Emoji name="coffe"/>) bla bla bla</Text>`

But keeps not working the result you can see below:

![image](https://user-images.githubusercontent.com/4583856/28118873-ddceaa28-66e0-11e7-924f-789e3098fb81.png)

Someone has this same problem? Can help me?

Tks!

**Comment by fourestfire** [comment]
Try using coffee, coffe is a typo.
