### ISSUE TITLE
React.PropTypes in NPM Published Version 

### ISSUE THREAD

**Issue by reggie3** [EricPKerr/react-native-emoji#19]
The version of this package still has a reference to React.PropTypes.  The index.js file that is part of the package is not the same one as the repository.

**Comment by puradox** [comment]
While we wait for @jorilallo to publish the updated version, I've published an updated version to [`@ardentlabs/react-native-emoji`](https://www.npmjs.com/package/@ardentlabs/react-native-emoji)

```
    "@ardentlabs/react-native-emoji": "^1.2.1",
```

**Comment by EricPKerr** [comment]
npm version will be updated, thanks!
