### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by ltorroba** [EricPKerr/react-native-emoji#2]
PR #1 addressed the issue of the missing new emojis, such as `flag-br`, `flag-ar` and `scales`; however, as the package has not been republished to npm, users still end up getting the outdated version.

The fix would simply involve running `npm version patch` followed by `npm publish` by anyone with access to the package in npm (I'm assuming only @jorilallo).

**Comment by jorilallo** [comment]
@zesme sorry, forgot this earlier. I'll publish the latest later today

**Comment by jorilallo** [comment]
@zesme updated!
