### ISSUE TITLE
Issue with importing

### ISSUE THREAD

**Issue by TANemesis** [EricPKerr/react-native-emoji#20]
Once I add the line

`import Emoji from 'react-native-emoji';`

at the top of my file and reload the app on iOS, I start seeing an error:

> Cannot read property 'string' of undefined

If I remove that import statement, the app builds and runs fine.

**Comment by TANemesis** [comment]
Actually, this issue and issue #19 are related. The `index.js` file in this repo is not the same as the one in the npm package. If you replace the contents of the one installed via npm with the contents of `index.js` in this repo, it works fine. Please update the npm package.

**Comment by tthsympa** [comment]
+1 please upgrade the npm package !

**Comment by Winglonelion** [comment]
i met it. For quick resolve it, i installed it directly via github. 
```npm install react-native-emoji@https://github.com/jorilallo/react-native-emoji -S```

**Comment by EricPKerr** [comment]
Hi @jorilallo can you please take a look at this? There needs to be a new npm version published. Merging #21 or #15 would be appreciated as well.  Thanks!

**Comment by noudadrichem** [comment]
I repeat @EricPKerr , you should publish an update to NPM. @TANemesis

**Comment by jorilallo** [comment]
As it's probably clear, I don't have much interested in maintaining this module as I don't work onRN anymore (also, the code is pretty shit from my learning days). If anyone is interested in taking this over, happy to transfer the repo and package over. Just show me some proof that you have previously maintained a package or have other relevant experience. To others, it's like two lines of code, you're probably better on coding this yourself.

**Comment by noudadrichem** [comment]
@jorilallo It is working from git, and not from NPM. Just throw a new publish and it works. 😝

**Comment by EricPKerr** [comment]
@jorilallo I'd be happy to take this over, the changes and maintenance should be fairly straightforward.  The biggest thing is transferring https://www.npmjs.com/package/react-native-emoji ownership so I can publish new releases. My username is EricPKerr on both.

**Comment by EricPKerr** [comment]
Hi @jorilallo - any update here?  I'd be glad to take over maintaining this module.  Thanks

**Comment by jorilallo** [comment]
@EricPKerr trafferred the access to you on both, go at it :)

**Comment by EricPKerr** [comment]
@jorilallo perfect, thanks!
