### ISSUE TITLE
Found 2 vulnerabilities (1 low, 1 high) in project package

### ISSUE THREAD

**Issue by clemente-xyz** [EricPKerr/react-native-emoji#28]
Hi guys!

You need to fix some vulnerabilities in your project:

<img width="496" alt="screenshot 2018-12-07 at 12 29 35" src="https://user-images.githubusercontent.com/9727036/49656310-c9b5dc80-fa1b-11e8-84dc-156fac050166.png">

Hope this help 😃

**Comment by EricPKerr** [comment]
The `node-emoji` dependency pulls in the lodash `4.4.0` but I don't know what's pulling in `ws` - are you sure that's related to this library?
