### ISSUE TITLE
Solved: Android Opacity

### ISSUE THREAD

**Issue by marcpechaitis** [EricPKerr/react-native-emoji#32]
Posting here in case it saves someone in the community from a little grief.

I just solved an issue I faced where my emoji were appearing perfectly fine on iOS, but when displayed on Android they were not using full opacity even though I set the `opacity: 1.0` in the style prop (against a dark-grey background).

The solution is to use `color: '#000000'` in the style prop for the Emoji itself.

([hat tip](https://stackoverflow.com/questions/50840047/emojitextview-renders-emoji-semi-transparent))

**Comment by EricPKerr** [comment]
@marcpechaitis thanks!  I released version 1.7.0 with a default style color prop that should fix this.
