### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by matsossah** [EricPKerr/react-native-emoji#6]
Trying to get it to work with android but I just get a blank space.  Is this supposed to support both platforms?

**Comment by mattisx** [comment]
@matsossah It's working well for me as of today, running RN 0.38.

Simple example:

```
import Emoji from 'react-native-emoji';

...

render() {
	return (
		<View>
			<Text><Emoji style={{fontSize: 40 }} name="fork_and_knife"/></Text>
		</View>
	);
}
```

**Comment by sibelius** [comment]
@matsossah do u still have this problem?

**Comment by PARAGJYOTI** [comment]
Same issue here

**Comment by liuzhen88** [comment]
I have same problem, react native version is 0.42.3

**Comment by zzlandroid** [comment]
in my opinion , i find  that propTypes   is not work well

**Comment by EricPKerr** [comment]
`Version 1.3.0` was just published to NPM.  Can someone with this error please update and check?  Thanks
